### ISSUE TITLE
The baseline profile install broadcast was not received. This most likely means that the profileinstaller library is missing from the target apk

### ISSUE THREAD

**Issue by beyondckw** [android/performance-samples#135]
I change the compilationMode to CompilationMode.Partial，other  the same as origin project
AS: bumblebee

@Test
    fun startup() = benchmarkRule.measureRepeated(
        packageName = TARGET_PACKAGE,
        metrics = listOf(StartupTimingMetric()),
        compilationMode = CompilationMode.Partial(),
        iterations = 5,
        startupMode = StartupMode.COLD
    ) {
        pressHome()
        startActivityAndWait()
    }

**Comment by beyondckw** [comment]
I already added implementation("androidx.profileinstaller:profileinstaller:1.2.0-alpha02")

**Comment by mlykotom** [comment]
Could you give us more details on what device, OS version do you run the benchmarks? Thank you

**Comment by beyondckw** [comment]
oneplus a5010 , android 11

**Comment by qavan** [comment]
same on honor 9c

**Comment by mehmet6parmak** [comment]
same on huawei mate 20 pro

**Comment by mehmet6parmak** [comment]
It worked after turning off battery optimizations. Hope this helps to others.

**Comment by roliveiravictor** [comment]
Huawei mate 20 pro - Adding `androidx.profileinstaller:profileinstaller:1.2.0`, turning off battery optimizations and disabling (might stuck the app restart if not) the app launch manager has solved my issue.

**Comment by hellosagar** [comment]
It's still happening, even tho I've the dependency :(
```
  implementation("androidx.profileinstaller:profileinstaller:1.3.1")
```

**Comment by dil33p** [comment]
Even I am facing the same issue,not working with MotoE, OnePlus and Pixel. Could there be any other issue. I am using 
implementation("androidx.profileinstaller:profileinstaller:1.3.1") with Gradle 8.2

**Comment by CedrickFlocon** [comment]
it also seems that debuggable application lead to this error.
