### ISSUE TITLE
Unable to read any metrics during benchmark

### ISSUE THREAD

**Issue by beyondckw** [android/performance-samples#137]
androidx.benchmark:benchmark-macro-junit4:1.1.0-beta04

```
java.lang.IllegalArgumentException: Unable to read any metrics during benchmark (metric list: [androidx.benchmark.macro.StartupTimingMetric@ac86f88]).
Check that you're performing the operations to be measured. For example, if
using StartupTimingMetric, are you starting an activity for the specified package
in the measure block?
	at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmark(Macrobenchmark.kt:237)
	at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmarkWithStartupMode(Macrobenchmark.kt:301)
	at androidx.benchmark.macro.junit4.MacrobenchmarkRule.measureRepeated(MacrobenchmarkRule.kt:102)
	at androidx.benchmark.macro.junit4.MacrobenchmarkRule.measureRepeated$default(MacrobenchmarkRule.kt:92)
	at com.example.benchmark.BaselineProfileBenchmark.startup(BaselineProfileBenchmark.kt:40)
	at com.example.benchmark.BaselineProfileBenchmark.startupNoCompilation(BaselineProfileBenchmark.kt:31)
```

**Comment by mlykotom** [comment]
We're currently trying to resolve it in this [issue](https://buganizer.corp.google.com/issues/218668335#comment27).

As a workaround, could you try adding some `Thread.sleep(500)` to the `measureRepeated`?

**Comment by beyondckw** [comment]
Yes, i do, but it's not working.

**Comment by mlykotom** [comment]
We've done some stability improvements. Could you check with the latest version `rc01` if the problem still persists?
Thanks!

**Comment by zeac** [comment]
The problem is still here in `1.1.0` on the devices lower than API level 29 if release build of the app is used. Some mandatory traces, like `startActivityAndWait` are missing from captured .trace files because release builds are not traceable.

Starting API 29 there is a [new manifest flag](https://developer.android.com/guide/topics/manifest/profileable-element) which allows to collect traces from release builds when set on both the app and the test app.

The only way to make it work on API 28 is to use debug builds.

**Comment by keyboardsurfer** [comment]
When relying on debug builds for benchmarking you won't be able to see real world performance of your app.
The macrobenchmark library works down to API 23. Some traces might not be available depending on the specific device you're using. Which device & OS version are you using to capture traces?

**Comment by YashNagayach95** [comment]
> When relying on debug builds for benchmarking you won't be able to see real world performance of your app. The macrobenchmark library works down to API 23. Some traces might not be available depending on the specific device you're using. Which device & OS version are you using to capture traces?

Same issue on Redmi 7A. 2GB RAM

**Comment by mlykotom** [comment]
This is unfortunately correct.

As you mentioned, you can use `debug` builds, but these are not recommended for performance measuring.

Alternatively, you should be able to measure `release` build on rooted device.

Here's nothing we can do better, because that's how Android system was designed.
