### ISSUE TITLE
What does "frameoverrunnanos" mean - JankStats

### ISSUE THREAD

**Issue by zijinzhiyun** [android/performance-samples#144]
FrameDataApi31.java

Log : FrameData(frameStartNanos=769350421608955, frameDurationUiNanos=4858809, frameDurationCpuNanos=9390944, frameOverrunNanos=9222602686413166853, isJank=false, states=[])

isJank=false，but frameOverrunNanos is positive value

**Comment by ChrisCraik** [comment]
Not only is it positive, it looks far too large, like it's been calculated incorrectly. Can you please file a library bug here describing how you reproduced this: https://issuetracker.google.com/issues/new?component=1109743&template=1621342

**Comment by zijinzhiyun** [comment]
@ChrisCraik 
sorry,I can't access this website.

Activity only have a EditTextView, wait a minute, FrameMetrics.getMetric(FrameMetrics.TOTAL_DURATION) is large(9.2225657E12). 

FrameMetrics: -------------UNKNOWN_DELAY_DURATION: 1514772
FrameMetrics: -------------INPUT_HANDLING_DURATION: 6093
FrameMetrics: -------------ANIMATION_DURATION: 3438
FrameMetrics: -------------LAYOUT_MEASURE_DURATION: 907812
FrameMetrics: -------------SYNC_DURATION: 263906
FrameMetrics: -------------COMMAND_ISSUE_DURATION: 1247344
FrameMetrics: -------------SWAP_BUFFERS_DURATION: 1770885
FrameMetrics: -------------INTENDED_VSYNC_TIMESTAMP: 806762203381794
FrameMetrics: -------------VSYNC_TIMESTAMP: 806762203381794

device: Redmi K40, OS: 12.

I only have this phone, but I didn't find this problem on the emulator.

**Comment by mlykotom** [comment]
Hi, checking in if you're still able to reproduce the problem? 
Thanks!
