### ISSUE TITLE
Macroprofile doesn't work with Android Studio BumbleBee

### ISSUE THREAD

**Issue by snijsure** [android/performance-samples#145]
The documentation says one can use Android Studio BumbleBee to build project, but MacroProfile doesn't work because of android gradle plugin version 7.2.0-beta04, if one downgrades to plugin 7.0.X project at least builds.

Does one need to use 7.2.0-beta04 for Macroprofile to work properly?

**Comment by mlykotom** [comment]
We updated the samples to use latest stable AGP so it should work with any version of Android Studio.
Thanks for reporting!

**Comment by snijsure** [comment]
Thank you @mlykotom 🙇 👍
