### ISSUE TITLE
Can't setup macro-bench different product flavor (we cannot choose between the following variants of project )

### ISSUE THREAD

**Issue by yadavraju** [android/performance-samples#161]
How Can I setup macro-bench different product flavors (we cannot choose between the following variants of the project )

```
* What went wrong:
Could not determine the dependencies of task ':libraries:macrobenchmark:connectedBenchmarkAndroidTest'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':libraries:macrobenchmark:benchmarkTestedApks'.
      > Could not resolve project :app.
        Required by:
            project :libraries:macrobenchmark
         > The consumer was configured to find a runtime of a component, as well as attribute 
```

**Comment by keyboardsurfer** [comment]
You're describing an issue in your own implementation rather than the sample code.
At this point I am unable to reproduce this as the sample does not make use of flavors.
Could you try to reproduce the issue on a fork of this repository or [create a MRE](https://stackoverflow.com/help/minimal-reproducible-example) of your own for this?

**Comment by Pittvandewitt** [comment]
There are 2 possible workarounds I have found so far:
- Downgrade to Android Gradle Plugin version 7.0.4
- Recreate the same flavors in your benchmark module and select the matching build variant manually

Neither solutions are ideal, so a new sample showcasing how to configure Gradle properly for multiple flavors would be much appreciated.

**Comment by mlykotom** [comment]
There are 2 options to work with flavors and multi modules:

1) as you mentioned, add `productFlavors` to the `:macrobenchmark` module with the same definition as your `:app` module. This will allow you to benchmark any of your product flavors (if there are some performance differences).

2) You can instead add `missingDimensionStrategy` 

```
defaultConfig { 
  missingDimensionStrategy "platform", "google"
}
```
This allows benchmarking just the specified product flavor. In your case it may be enough.

**Comment by keyboardsurfer** [comment]
Please take a look at the implementation of macrobenchmark in the [Now in Android](https://github.com/android/nowinandroid/blob/main/app/build.gradle.kts#L55) application. It features product flavors and is configured to run benchmarks in the intended way.
