### ISSUE TITLE
How to findObject if my applicationId and packageName name of application is different 

### ISSUE THREAD

**Issue by yadavraju** [android/performance-samples#168]
Eg: 
` Application_Id=com.raju.center` (this is the application I am trying to benchmark) but my package name is `com.app.center` inside that package, I have an activity that has a fragment that contains the Recycler view I want to access to recycleViewId but it gives null pointer exception because this code `val recycler = device.findObject(By.res(packageName, "recycler")) ` looking inside com.raju.center but my code package structure is different I also tried using a direct class-level package name it doesn't work either also tried adding content description it doesn't work for some reason. I don't want to use `val recycler = device.findObject(By.scrollable(true))` for now

How to find viewObject ? (In the performance sample all the activity is in the same package and have the same application id and package name ) I tried changing the sample with different applicationId and package names those tests are failing
 
           val recycler = device.findObject(By.res(packageName, "recycler"))
            // Set gesture margin to avoid triggering gesture navigation
            // with input events from automation.
            recycler.setGestureMargin(device.displayWidth / 5) //getting null pointer exception

            // Scroll down several times
            repeat(3) { recycler.fling(Direction.DOWN) }

**Comment by keyboardsurfer** [comment]
It seems like you're describing an issue that is not directly related to the sample.
Please use [StackOverflow](stackoverflow.com) for issues related to your modified implementation.
