### ISSUE TITLE
Could not validate the dex paths: Unmatched .dm files: [release.dm]

### ISSUE THREAD

**Issue by bringogo** [android/performance-samples#174]
I follow https://developer.android.google.cn/topic/performance/baselineprofiles#measuring-improvements to measure the improvement, but got warning when doing :
% adb install-multiple app-release.apk release.dm 
adb: failed to finalize session
Warning [Could not validate the dex paths: Unmatched .dm files: [release.dm]]
Success

Does it mean  fail to sideload the Baseline Profile ? how can i fix this ? please help ~

My adb version:
Android Debug Bridge version 1.0.41
Version 31.0.2-7242960
Installed as /usr/local/bin/adb

**Comment by mivanzhang** [comment]
same questions

**Comment by mivanzhang** [comment]
I got the same error, even the code can pass macrobenmark

**Comment by mivanzhang** [comment]
anyone helper here?

**Comment by L5411** [comment]
```
# Unzip the Release APK first
unzip release.apk

# Create a ZIP archive
# Note: The name should match the name of the APK
# Note: Copy baseline.prof{m} and rename it to primary.prof{m}
cp assets/dexopt/baseline.prof primary.prof
cp assets/dexopt/baseline.profm primary.profm

# Create an archive
zip -r release.dm primary.prof primary.profm

# Confirm that release.dm only contains the two profile files:
unzip -l release.dm
# Archive:  release.dm
#   Length      Date    Time    Name
# ---------  ---------- -----   ----
#      3885  1980-12-31 17:01   primary.prof
#      1024  1980-12-31 17:01   primary.profm
# ---------                     -------
#                               2 files

# Install APK + Profile together
adb install-multiple release.apk release.dm
```
Note:
1. Copy `baseline.prof{m}` and rename it to `primary.prof{m}`, zip them not with path
2. The `*.dm` name should match the package name of the APK: `{packageName}.dm` 
3. The APK name should match the package name of the APK: `{packageName}.apk` 

then run this:
```
adb install-multiple {packageName}.apk {packageName}.dm
```

**Comment by mivanzhang** [comment]
so the document need to update, https://developer.android.com/topic/performance/baselineprofiles#measuring-baseline, now is still release
