### ISSUE TITLE
MacrobenchmarkSample doesn't run with Android Studio Electric Eel

### ISSUE THREAD

**Issue by yschimke** [android/performance-samples#176]
Trying to run a macrobenchmark test from the editor.

![image](https://user-images.githubusercontent.com/231923/189125650-18e1daf3-0cc5-4541-a855-6db917e1abb5.png)

Works with Dolphin

**Comment by yschimke** [comment]
Using 

```
Android Studio Electric Eel | 2022.1.1 Canary 10
Build #AI-221.6008.13.2211.8963757, built on August 18, 2022
Runtime version: 11.0.15+0-b2043.56-8887301 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.17.11-1rodete2-amd64
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    wu.seal.tool.jsontokotlin (3.7.4)
    idea.plugin.protoeditor (221.6008.13)
    de.ehmkah.projects.imgdiff (1.11.0)
    com.developerphil.adbidea (1.6.6)

Current Desktop: GNOME
```

**Comment by keyboardsurfer** [comment]
I can't verify this on EE with the latest changes on `main`. Please verify if this problem still exists.

**Comment by yschimke** [comment]
I've got Flamingo now, but same issue still happening.

Curiously, in the launcher, an "Android App" shows "macrobenchmark.app.main" but no androidTest modules.
"Android Instrumented Tests" shows only androidTest modules, and macrobenchmark doesn't have one.

I wonder if it's that?

**Comment by carlonzo** [comment]
I got the same problem. in the list of modules I cant find anymore the `benchmark` module so I cant start the test from AS EE

**Comment by keyboardsurfer** [comment]
I can reproduce this issue now. It's not an issue with the code sample but appears to be a problem with Android Studio.
Please file an issue against [Android Studio](https://goo.gle/android-studio-issue) and link it here so we can follow up.

You can use the gutter icon (>>) to run the benchmarks in the meantime.
<img width="444" alt="Screen Shot 2022-10-07 at 11 45 30" src="https://user-images.githubusercontent.com/336005/194536027-90e63be1-8454-455b-8674-cfe87804c4d2.png">

Also, running benchmarks directly from Gradle is not impacted by this problem.

**Comment by yschimke** [comment]
https://issuetracker.google.com/issues/251780385

**Comment by mlykotom** [comment]
Android Studio stopped selecting the proper build type.
As a workaround until the issue is solved, you can open the Build Variants and select the `benchmark` build type for the `:app` module and then run the tests as usual.
