### ISSUE TITLE
Document how to run on a single connceted device

### ISSUE THREAD

**Issue by yschimke** [android/performance-samples#179]
Presumably with 

```
ANDROID_SERIAL=XXXX
```

Otherwise tests run on all or a random device?

**Comment by keyboardsurfer** [comment]
This sample assumes only one attached device at a time.
Your approach works and there's another mentioned on [StackOverflow](https://stackoverflow.com/questions/23960667/running-gradles-connectedandroidtest-on-a-specific-device)
