### ISSUE TITLE
Profile is empty exception shown while generating baseline profile

### ISSUE THREAD

**Issue by nitinsethi86** [android/performance-samples#182]
I ran the generate class BaselineProfileGenerator in Android 11, non Google play service rooted device. 

This the exception I get. 

09-18 10:28:55.871  9313  9335 E TestRunner: java.lang.IllegalStateException: The profile is empty.
09-18 10:28:55.871  9313  9335 E TestRunner: 	at androidx.benchmark.macro.BaselineProfilesKt.profile(BaselineProfiles.kt:117)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at androidx.benchmark.macro.BaselineProfilesKt.collectBaselineProfile(BaselineProfiles.kt:81)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at androidx.benchmark.macro.junit4.BaselineProfileRule.collectBaselineProfile(BaselineProfileRule.kt:89)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at com.example.macrobenchmark.BaselineProfileGenerator.generate(BaselineProfileGenerator.kt:40)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at androidx.benchmark.macro.junit4.BaselineProfileRule$applyInternal$1.evaluate(BaselineProfileRule.kt:76)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:134)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:128)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:27)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
09-18 10:28:55.871  9313  9335 E TestRunner: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
09-18 10:28:55.871  9313  9335 E TestRunner: ----- end exception -----
09-18 10:28:55.872  9313  9335 I TestRunner: finished: generate(com.example.macrobenchmark.BaselineProfileGenerator)

java.lang.IllegalStateException: The profile is empty.
at androidx.benchmark.macro.BaselineProfilesKt.profile(BaselineProfiles.kt:117)
at androidx.benchmark.macro.BaselineProfilesKt.collectBaselineProfile(BaselineProfiles.kt:81)
at androidx.benchmark.macro.junit4.BaselineProfileRule.collectBaselineProfile(BaselineProfileRule.kt:89)
at com.example.macrobenchmark.BaselineProfileGenerator.generate(BaselineProfileGenerator.kt:40)

**Comment by nitinsethi86** [comment]
is it possible that it's happening coz I didn't invoke adb root? 

If so, cam we add it in the exception message?

**Comment by keyboardsurfer** [comment]
I can't reproduce this error with the sample. Please verify it's still occurring with the current state of `main`.

**Comment by jamieadkins95** [comment]
I was getting this in the sample and in our own project when running on an api 30 emulator. It was flaky too, like 1 in 5 runs would work.

I haven't seen this on API 31
