### ISSUE TITLE
Re-enable ScrollBenchmarks

### ISSUE THREAD

**Issue by keyboardsurfer** [android/performance-samples#207]
Currently disabled as we can't see whether there is a scrollable view on screen.
If there's none this causes many failures, slowing down the process.
To re-enable we need 1) a way to check if a scrollable view is present 2) run the benchmarks only if 1) is true.

**Comment by mlykotom** [comment]
Over to you, Ben. Or maybe this could be done by @yenerm ?

**Comment by keyboardsurfer** [comment]
Murat, could you take a look at this one please?

**Comment by yenerm** [comment]
This is merged https://github.com/android/performance-samples/pull/242
