### ISSUE TITLE
StartupMode.Cold will close app after 1 iteration

### ISSUE THREAD

**Issue by doniwinata0309** [android/performance-samples#215]
If you try scenario scrollNestedRecyclerWithoutRecyclerPool, it will just close app after 1 iteration.

I am using macrobenchmark version 1.2.0-alpha11. 

This also happen to my app, is there bug with library ?

**Comment by mlykotom** [comment]
Macrobenchmark kills the app after `setupBlock` when using `StartupMode.COLD`.
This was changed in 1.2.0-alpha07. The apropriate way of benchmarking scrolling when there's need to navigate to a certain screen is using `StartupMode.WARM` or `null` (default parameter).
