### ISSUE TITLE
Error: Run configuration ExampleStartupBenchmark is not supported in the current project. Cannot obtain the package.

### ISSUE THREAD

**Issue by dogancankilic** [android/performance-samples#217]
When I click on Run action for the purpose of running the vanilla benchmark test Edit Configuration dialog appears with this error.

**Comment by vpmalley** [comment]
I got that same error, on the Flamingo version of Android Studio (2022.2.1 Patch 1) and on some previous versions. I tried adding the package to all manifest files I have, I can't find a solution.

**Comment by datienza** [comment]
@vpmalley I got same error, could you please be more specific of what you exactly changed in the code to make it work? Do you mean it here? 

```
androidComponents {
    beforeVariants(selector().all()) {
        it.enable = it.buildType == "benchmark"
    }
}
```

Thanks v much!

**Comment by manaswiniFlipp** [comment]
@vpmalley i am getting the same error. can you please be more descriptive and explain how you solved this error? A sample code snippet should be very helpful. Thank you.

**Comment by keyboardsurfer** [comment]
Does this issue occur in this sample repository with the latest stable release of Android Studio (Hedgehog)?

**Comment by keyboardsurfer** [comment]
This issue is considered stale. We are missing input to take further action.  
If the problem persists, please file a [new issue](new) with the missing information and link back to this issue.

**Comment by vpmalley** [comment]
@manaswiniFlipp here is an example if that can help:

in my main module `build.gradle` file, I added the `benchmark` build type:
```
android {
    buildTypes {
        benchmark {
            signingConfig signingConfigs.debug
            matchingFallbacks = ['release']
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'benchmark-rules.pro'
        }
    }
}
```
As I also had product flavors, I had to add the same to the `build.gradle` file of the benchmark module:

```
android {
    flavorDimensions "sweetFlavor"
    productFlavors {
        vanilla {
            dimension "sweetFlavor"
        }
        strawberry {
            dimension "sweetFlavor"
        }
    }
}
```

And when running the benchmark module, I have to select an entire build variant with a flavor, i.e. `vanillaBenchmark`
