### ISSUE TITLE
ScrollBenchmark Fling Behavior on Large Screens

### ISSUE THREAD

**Issue by dogancankilic** [android/performance-samples#218]
Should fling behavior work fine for TvLazyColumns / TvLazyRows on large screens?

**Comment by mlykotom** [comment]
Passing to @pflammertsma as the TV expert. It's possible that on TV you may need to use different gesture to go over the column/row. 

@pflammertsma is the TV remote mimicking any gesture that we could use with UiAutomator? Thanks

**Comment by pflammertsma** [comment]
TvLazyColumns and Rows currently do not support gestures as they are specialized components for TV. I suggest using a different ViewModel to bring relevant components for touch surfaces, separate from TV. ("[Large screens](https://developer.android.com/large-screens)" in Google's terminology does not include TV.)

If this is something you'd like to see supported, please provide some more context in a feature request: https://developer.android.com/jetpack/androidx/releases/tv#feedback
