### ISSUE TITLE
Package x.y.z must not be running prior to cold start!

### ISSUE THREAD

**Issue by nuhkoca** [android/performance-samples#221]
Hello,

I am trying to integrate Baseline Profiles but when I execute StartupBenchmark with COLD startup mode, it throws an exception

> Package x.y.z must not be running prior to cold start!

Do you know why?

My config:

```kotlin
@RunWith(AndroidJUnit4::class)
class StartupBenchmark {

    @get:Rule
    val benchmarkRule = MacrobenchmarkRule()

    @Test
    fun startup() = benchmarkRule.measureRepeated(
        packageName = PACKAGE_NAME,
        metrics = listOf(StartupTimingMetric()),
        iterations = 5,
        startupMode = StartupMode.COLD
    ) {
        pressHome()
        startActivityAndWait()
    }
}
```

**Comment by nuhkoca** [comment]
I noticed that this happens if `iterations` is greater than `3`

**Comment by mlykotom** [comment]
Could you give a bit more details on what device, OS version you encountered the error?

The error occurs because Macrobenchmark is not able to kill your app.  But it does it in between iterations, so I don't know why changing the `iterations` would make a difference.

**Comment by nuhkoca** [comment]
The device is Samsung S21 5G Android 13.

**Comment by SubhrajyotiSen** [comment]
Noticing this issue on Pixel 6a running Android 14 Beta 2 as well.

**Comment by mlykotom** [comment]
Could you pls file a bug directly to the library? This doesn't look like a bug with the sample https://b.corp.google.com/issues/new?component=975669&template=1519452 

Thank you! 🙏🏼

**Comment by rishabh876** [comment]
Looks like this has now been fixed in version 1.2.4 of `benchmark-baseline-profile-gradle-plugin`
https://developer.android.com/jetpack/androidx/releases/benchmark#1.2.4

**Comment by whlk** [comment]
I know this issue is closed, but as it is the first result in Google I wanted to post a workaround: Add a short delay to `pressHome()`, this allows for the process kill to finish before the next iteration starts. 

```
@RunWith(AndroidJUnit4::class)
class ExampleStartupBenchmark {
  @get:Rule
  val benchmarkRule = MacrobenchmarkRule()

  @Test
  fun startup() = benchmarkRule.measureRepeated(
      packageName = PACKAGE_NAME,
      metrics = listOf(StartupTimingMetric()),
      iterations = 5,
      startupMode = StartupMode.COLD
  ) {
    pressHome(3000)
    startActivityAndWait()
    killProcess()
  }
}
```

**Comment by keyboardsurfer** [comment]
Both starting and killing the process is taken care of by the MacrobenchmarkRule. I do not recommend using above workaround.

Please update to version [1.4.0-alpha03](https://developer.android.com/jetpack/androidx/releases/benchmark#1.4.0-alpha03) or newer where this issue has been addressed and fixed.

**Comment by keyboardsurfer** [comment]
Please file an [issue](https://issuetracker.google.com/issues/new?component=975669&template=1519452) with relevant details so we can continue investigating and potentially resolving this problem for good. 

@SubhrajyotiSen 
@whlk

**Comment by piotrgomola** [comment]
I am also seeing it in my tests (I am on 1.4.0-alpha06), is there an issue created on issuetracker for that?

**Comment by ChrisCraik** [comment]
This is the issue for this crash: http://issuetracker.google.com/issues/351582215

If you're seeing this in 1.4.0-alpha03+, you have the latest speculative fix. If you can add a specific repro project (or pr on the sample, with either the sample app or prod app from play), that would help us investigate further.
