### ISSUE TITLE
Benchmark Tests do not run in Android Version 11

### ISSUE THREAD

**Issue by JyotimoyKashyap** [android/performance-samples#222]
I have been trying to get my hands on benchmarking for a long time now. It seems to work fine on physical devices with android 13 but doesn't seem to to work on android 11. 

Below is the logcat screenshot : 
![Screenshot 2023-04-18 at 12 56 49 PM](https://user-images.githubusercontent.com/55136058/232703351-86b240ad-c813-4ba5-9a8b-37330039239f.png)

Is there any workaround this, since, it is important to benchmark an app in different android versions.

**Comment by mlykotom** [comment]
What version of macrobenchmark do you use? Could you try with latest version as we had some fixes related to permissions in 1.2. Thanks!

**Comment by keyboardsurfer** [comment]
This issue is stale. We are missing input to take action. If the problem persists, please file a new issue with the missing information and link back to this issue.
