### ISSUE TITLE
Switch to benchmark test runner 

### ISSUE THREAD

**Issue by yschimke** [android/performance-samples#235]
Macrobenchmark now prompts to use this, so samples should probably follow the advice.

androidx.benchmark.junit4.AndroidBenchmarkRunner

https://developer.android.com/reference/kotlin/androidx/benchmark/junit4/AndroidBenchmarkRunner

**Comment by yschimke** [comment]
Is it a bad idea to use this runner? I changed another project already.

**Comment by ChrisCraik** [comment]
It's only needed for microbenchmarks. The warning shouldn't show up for macrobenchmarks - and actually, I didn't ever see it for macro in internal AndroidX builds, not sure why not though.

**Comment by yschimke** [comment]
In my case I have some macrobenchmark run with a service (media session), so I suspect my case is still valid.
