### ISSUE TITLE
jankFrameListener run 2 times for onCreate

### ISSUE THREAD

**Issue by prabhat1707** [android/performance-samples#236]
```
FrameData(frameStartNanos=8841146369258, frameDurationUiNanos=69020289, frameDurationCpuNanos=74082747, isJank=true, states=[prabhat_Activity: MainActivity])

ActivityManager         system_process                       I  Displayed com.example.myapplication/.ui.MainActivity: +127ms

FrameData(frameStartNanos=8841221785642, frameDurationUiNanos=7009654, frameDurationCpuNanos=9558113, isJank=false, states=[prabhat_Activity: MainActivity])
```
**in the above sequence, frame rate logs callback run 2 times for activity onCreate . how this is possible ?**

**Comment by keyboardsurfer** [comment]
Thank you for reporting this issue. The information provided is not enough for to investigate the problem you are facing. Please provide information that can help us reproduce it.

**Comment by prabhat1707** [comment]
Basically , I got a point why it running 2 times but not a way to differentiate from which screen it's called,

So, I have an activity and fragment on top of it. I add putState in onCreate of activity so, it send event 2 times i.e 1 for activity and 1 for fragment but I didn't add putState in fragment.
How I can differentiate ?

**Activity**
```
val metricsStateHolder = PerformanceMetricsState.getHolderForHierarchy(binding.root)
jankStats = JankStats.createAndTrack(window, jankFrameListener)
metricsStateHolder.state?.putState("prabhat_Activity", javaClass.simpleName)
```
**Fragment**
Removed all code related to junk state bt still got it 2 time, bt when i remove adding fragment on top of activity then it only calls 1 times.

**Comment by keyboardsurfer** [comment]
Thanks for adding these details.
It seems like you're describing an issue that is not directly related to the sample.
Please use [StackOverflow](stackoverflow.com) for issues related to your modified implementation.
Feel free to link your question here.

**Comment by keyboardsurfer** [comment]
We need your input to act on this issue.
This issue will be closed soon unless there is further actionable input.

**Comment by keyboardsurfer** [comment]
This issue is considered stale. We are missing input to take further action.  
If the problem persists, please file a [new issue](new) with the missing information and link back to this issue.
