### ISSUE TITLE
Does matchingFallbacks work if libraries are imported via releaseImplementation and debugImplementation?

### ISSUE THREAD

**Issue by sudhirkhanger** [android/performance-samples#250]
I have setup the benchmark module for macrobenchmark as per the document but libraries in my project come in `release` and `debug` format and are implemented as such using `releaseImplementation` and `debugImplementation`.

When I switch to benchmark variant it refuses to resolve classes from the library as there is no benchmark type.

Also `build.gradle.kts` files don't have anything like `benchmarkImplementation`. I have added `matchinfFallback` but I suppose it doesn't work if you are using specific build type with implementation.

Any solution to this issue?

**Comment by keyboardsurfer** [comment]
It seems like you're describing an issue that is not directly related to the sample.
Please use [StackOverflow](stackoverflow.com) for issues related to your implementation.

If possible add more details to a question there and link it here.
