### ISSUE TITLE
Samples doesn't work for dynamic feature modules

### ISSUE THREAD

**Issue by Hessesian** [android/performance-samples#251]
Hi, I implemented these samples into official sample for acessing dynamic feature modules 
https://github.com/Hessesian/android-dynamic-code-loading

And when running the benchmark, it will not load the dynamic feature module data, presumably because of install command from android test plugin that will only install main apk instead of entire bundle, any suggestions or workarounds ? Thanks

**Comment by keyboardsurfer** [comment]
Currently Baseline Profiles and running benchmarks are not supported when using dynamic feature modules.

**Comment by Hessesian** [comment]
Thanks for clarification, are there any plans on supporting this ? We have a project where core features are setup as install-time dynamic features and if we should change it to library, depending on planned support for this

**Comment by keyboardsurfer** [comment]
We're working through several issues around feature modules with benchmarking. Have you tried fused install time modules?

**Comment by keyboardsurfer** [comment]
Also, [this is likely the issue](https://issuetracker.google.com/216057468) you have described above.
