### ISSUE TITLE
[JankStat] [Feature] Provide expectedDuration of Frame in FramaData

### ISSUE THREAD

**Issue by iamkdblue** [android/performance-samples#253]
For example in - **JankStatsApi24Impl** - have **expectedDuration** field and  from **JanksStatsApi31Impl** - have **getExpectedFrameDuration**, it will be very helpful for developer to  calculate custom metric where we need **expectedDuration** of frame. 

For Now 
JankStats For Api 24 - provides only - isJank, startTime, uiDuration and cpuDuration
JankStats For Api 31 - provides only - isJank, startTime, uiDuration, cpuDuration, totalDuration and overrun

**Comment by keyboardsurfer** [comment]
This is a feature request. Please file it on the [Google Issuetracker in the Metrics component](https://issuetracker.google.com/issues/new?component=1109743&template=1621342).
