### ISSUE TITLE
Question about the difference in file size inside the aab depending on the location of the generated baseline-prof.txt file

### ISSUE THREAD

**Issue by Veronikapj** [android/performance-samples#262]
1. In the case of creating `app-release.aab` from the existing location of the sample baselineProfiles in `release/generated/baselineProfiles`
`baseline.prof` size is 5.9k 
![image](https://github.com/android/performance-samples/assets/360685/02d4b8dd-0820-4853-a1d9-d9ed9103b87e)

2. In the case of creating `app-release.aab` after moving the same file to `main/generated/baselineProfiles`
`baseline.prof` size is 4.8k 
![image](https://github.com/android/performance-samples/assets/360685/7f2c9227-c1b5-48b5-9922-9500212905eb)

3. In the case of automatically generating the baseline profile file with the following option settings and including it when creating the aab
The size of baseline.prof is 4.8k, which is the same size as when the file is placed in the `main/generated/baselineProfiles` directory.

```
baselineProfile {
  variants {
    release {
      automaticGenerationDuringBuild = true
    }
  }
}
```

Even though it is the same `baseline-prof.txt`, the size of the converted baseline.prof inside the aab is different, with 5.9k for `release` and 4.8k for the case included in `main`. I am curious about the reason for this difference. And where should I put the generated `baseline-prof.txt` file to use in my service?

**Comment by keyboardsurfer** [comment]
This issue is considered stale. If the problem persists, please file a [new issue](new) with the missing information and link back to this issue.
