### ISSUE TITLE
Where and with what name to store the multiple profile

### ISSUE THREAD

**Issue by hellosagar** [android/performance-samples#271]
From the android doc I learnt that when a single baseline profile is generated, it needs to be renamed to `baseline-prof.txt` and copied to the `src/main/`

But with the multiple profiles which are generate from the 3 different generators which extended [BaselineProfileGeneratorScaffold](https://github.com/android/performance-samples/blob/4603b244b1c3b4fde89e25bba794889abddb6b7a/MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/baselineprofile/BaselineProfileGeneratorScaffold.kt#L34), Question is:
1. What name they should be renamed to?
2. Where to copy these multiple profiles into? 

Reference image of multiple profiles outside:
<img width="722" alt="Screenshot 2024-02-26 at 10 57 42 PM" src="https://github.com/android/performance-samples/assets/50016799/ec71872f-df6c-4da1-a7e0-5407706b3502">

Doc reference - https://developer.android.com/topic/performance/baselineprofiles/create-baselineprofile#create-new-profile-plugin:~:text=Locate%20the%20HRF%20file%20in,to%20baseline%2Dprof.txt.

**Comment by keyboardsurfer** [comment]
We recommend using the baseline profile Gradle plugin and [let it handle](https://developer.android.com/topic/performance/baselineprofiles/configure-baselineprofiles) where to put the source file.

Essentially, configure it to `saveInSrc` and possibly `mergeIntoMain` according to the documentation.

**Comment by keyboardsurfer** [comment]
You can put the profile files in `src/$variant/generated/baselineProfiles/$profileName.txt` as outlined in the [AGP version compatibility table](https://developer.android.com/topic/performance/baselineprofiles/overview#recommended-versions).

**Comment by hellosagar** [comment]
Thanks @keyboardsurfer Im excited to share the results in public soon :)

**Comment by keyboardsurfer** [comment]
Awesome! Looking forward to seeing them.

**Comment by scana** [comment]
Hey @keyboardsurfer I've noticed that if I put both my baseline and startup prof files under:
- `src/main/baselineProfiles/*`results in bigger `prof` file ending up in an APK (9,9KB)
- `src/main/generated/baselineProfiles/*` results in smaller `prof` file (6,4KB)

I assume this comes down from merging all files under `src/main/baselineProfiles` by default - is this something that I should be worried about?

**Comment by keyboardsurfer** [comment]
Thanks for bringing this up @scana. Could you file a bug against the [benchmarking library](https://issuetracker.google.com/issues/new?component=585351&template=1235073) and link it here? It's the best place to investigate and get a resolution for issues like this.
