### ISSUE TITLE
All Macrobenchmarking tests fail on both device & emulators & gradle/dependency issues

### ISSUE THREAD

**Issue by spark85** [android/performance-samples#281]
Hello, 

I ran the tests are per the Read.me document and all of the tests are failling!  Some are skipped. I've attached is an output log.  The I tried it on a Pixel 8 Emulator running API 34; with Android Studio Igauna AI-232.10203.10.2321.1104044, with java 11 & java 17.   Some of the tests are skipped.  I can see an activity opening with buttons to other activities  and a login screen but I don't see the buttons getting clicked or opening new activities.  All of the errors look like this 

com.example.macrobenchmark.benchmark.LoginBenchmark > loginWithUiAutomator[Pixel_8_API_34(AVD) - 14] [31mFAILED [0m
	java.lang.AssertionError: ERRORS (not suppressed): EMULATOR
	WARNINGS (suppressed):

There isn't very much detail so I'm not sure what's going on.  I also can't find the RECYCLER_VIEW activity in the project.  This project is pretty complicated.  Is there a simpler on available? 

[macrobenching_test_fail_with_errors_log.txt](https://github.com/android/performance-samples/files/15001526/macrobenching_test_fail_with_errors_log.txt)

I had also seen some sync and build errors about using gradle-8.0 and requiring an alpha versionn of 8.3.  The project ran so I ignored those issues. 

EDIT 

I was able to get it working on my Pixel XL.  My best guess is that it didn't have enough charge when I initially ran it.  However the tests seem to be stuck in a cycle.  It still hasn't completed after 30min.  Is that expected?

**Comment by keyboardsurfer** [comment]
> The I tried it on a Pixel 8 Emulator running API 34
> `java.lang.AssertionError: ERRORS (not suppressed): EMULATOR`
This is expected when running on an emulator. You won't get reliable benchmark results there. For debugging purposes you can [suppress these])https://developer.android.com/topic/performance/benchmarking/macrobenchmark-instrumentation-args?hl=en#suppresserrors).

> I also can't find the RECYCLER_VIEW activity in the project.
Check out the (AndroidManifest)[https://github.com/android/performance-samples/blob/570221d3f49d49e45af7970c04c1fe3a72d6df33/MacrobenchmarkSample/app/src/main/AndroidManifest.xml#L71] which points to the [RecyclerViewActivity](https://github.com/android/performance-samples/blob/570221d3f49d49e45af7970c04c1fe3a72d6df33/MacrobenchmarkSample/app/src/main/java/com/example/macrobenchmark/target/activity/clicklatency/RecyclerViewActivity.kt).
