### ISSUE TITLE
FrameMetrics deviation

### ISSUE THREAD

**Issue by Dimezis** [android/performance-samples#31]
I'm observing strange results of ConstraintLayout measure + layout time.
According to FrameMetrics data of this benchmark, the ConstraintLayout's full measure + layout time for single iteration is 16040790ns (it varies, but let's take this as an example). Note, that this number is not for a single frame, but a sum of all frames data from the start to the end of the benchmark.

I was confused by these kind of results, because it's much less, than I would expect from layout of this complexity.

So I decided to add some manual logging of layout process, which looks like this:

```
val start = System.nanoTime()
measureAndLayoutExactLength(container)
measureAndLayoutWrapLength(container)
val end = System.nanoTime()
Log.d(TAG, "measure + layout: " + (end - start))
```
Which printed the result of 289000360ns for the exact same iteration. So the difference was **18 times**!
Sometimes the deviation is less significant, like ~3 times, but FrameMetrics always give a much smaller number.

What's the reason for that and how this precision can be improved?

**Comment by Luis0648** [comment]
Google recupereth*#*#*#*#

**Comment by keyboardsurfer** [comment]
By now several releases of libraries have taken place which are likely to render this issue infeasible to follow up.
Apologies for not getting to this earlier.
