### ISSUE TITLE
Timed out waiting for process (com.example.benchmark.test)

### ISSUE THREAD

**Issue by radityagumay** [android/performance-samples#39]
**Specification**
Android version: Android P
Android device: XIAOMI MI A1
Android Studio: 
```
Android Studio 3.6 RC 1
Build #AI-192.7142.36.36.6071332, built on December 13, 2019
Runtime version: 1.8.0_212-release-1586-b4-5784211 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 8029M
Cores: 8
```

**Steps to reproduce**
1. clone this project
2. open the project
3. go to / create new benchmark test
4. run below script
```kotlin
benchmarkRule.measureRepeated {
	for (a in 0..10000) {
             Log.d("LogBenchmark", "the cost of writing this log method will be measured")
         }
}
```

**Expected behavior**
```
Testing started at 10.51 ...

12/31 10:51:37: Launching 'integerArtCacheAlloc()' on Xiaomi Mi A1.
Running tests

$ adb shell am instrument -w -r    -e debug false -e class 'com.example.benchmark.AutoBoxingBenchmark#integerArtCacheAlloc' com.example.benchmark.test/androidx.benchmark.junit4.AndroidBenchmarkRunner

Started running tests

benchmark:        X ns AutoBoxingBenchmark.integerArtCacheAlloc
Tests ran to completion.
```

`X` is a time 

**Actual behavior**
```
Testing started at 10.52 ...

12/31 10:52:22: Launching 'integerArtCacheAlloc()' on Xiaomi Mi A1.
Running tests

$ adb shell am instrument -w -r    -e debug false -e class 'com.example.benchmark.AutoBoxingBenchmark#integerArtCacheAlloc' com.example.benchmark.test/androidx.benchmark.junit4.AndroidBenchmarkRunner

Started running tests

Timed out waiting for process (com.example.benchmark.test) to appear on xiaomi-mi_a1-00ccaa190904.
```

**Comment by ZacSweers** [comment]
This is a sample repo. As mentioned in the [README](https://github.com/android/performance-samples#reporting-issues), you should file issues on the actual issue tracker.

**Comment by dlam** [comment]
Thanks @ZacSweers - issues definitely will get more attention on the issue tracker.

@radityagumay note that `benchmarkRule.measureRepeated` automatically loops the provided block so there is no need to manually loop yourself.

**Comment by daniel-waiguru** [comment]
Experiencing this issue 'Timed out waiting for process (packagename) to appear on google-pixel_6-192.168.100.18:5555' while trying to run the default startup benchmark created after creating the macrobenchmark module using Android Studio Jellyfish
Specification
Android Device - Pixel 6 Android 14
AGP Version: 7.2.2
Android Studio:
`Android Studio Jellyfish | 2023.3.1
Build #AI-233.14808.21.2331.11709847, built on April 12, 2024
Runtime version: 17.0.10+0-17.0.10b1087.21-11572160 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON`

This is happening on work project but when I create a separate project it runs well
`@RunWith(AndroidJUnit4::class)
class ExampleStartupBenchmark {
    @get:Rule
    val benchmarkRule = MacrobenchmarkRule()

    @Test
    fun startup() = benchmarkRule.measureRepeated(
        packageName = "packagename",
        metrics = listOf(StartupTimingMetric()),
        iterations = 5,
        startupMode = StartupMode.COLD
    ) {
        pressHome()
        startActivityAndWait()
    }
}`
