### ISSUE TITLE
Not able to run project MacrobenchmarkSample

### ISSUE THREAD

**Issue by AndreSand** [android/performance-samples#81]
Sample pages return 404

<img width="1157" alt="Screen Shot 2021-05-19 at 8 44 38 PM" src="https://user-images.githubusercontent.com/8283868/118916180-46369000-b8e3-11eb-8b4f-0fceaaec5fe2.png">

**Comment by ChrisCraik** [comment]
The project was merged into the `main` branch: https://github.com/android/performance-samples/tree/main/MacrobenchmarkSample and we removed the `macrobenchmark` branch.

Just realized the link is stale in the [pre-public docs](https://android.googlesource.com/platform/frameworks/support/+/androidx-main/benchmark/docs/macrobenchmark.md) in the androidx repo, is that where you got the above link from?

**Comment by ChrisCraik** [comment]
Fixed links in the repo with the commit above, and fixing the docs in androidx repo with https://android-review.googlesource.com/c/platform/frameworks/support/+/1714390

**Comment by AndreSand** [comment]
@ChrisCraik thank you for fixing the links :)
