### ISSUE TITLE
please retry with version 2020.3.1 or newer.

### ISSUE THREAD

**Issue by dylannaniel** [android/performance-samples#86]
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2020.3.1 or newer.
![image](https://user-images.githubusercontent.com/38413282/123608859-b8c75380-d831-11eb-8809-a8ad9a262495.png)

**Comment by fueerqan** [comment]
You can update the build gradle tools to 4.2.0
`classpath 'com.android.tools.build:gradle:4.2.0'`

**Comment by ChrisCraik** [comment]
Sorry for the late reply.

Android Studio 4.2 isn't officially supported by Jetpack Macrobenchmark, as new functionality in Studio and 7.0-beta Android Gradle Plugin is needed for certain features in Studio, namely trace linking, and auto-installing the target app when code is changed (respectively).

You can still use Studio / AGP 4.2 if you like, but these features will not work, and you'll need to use a different  project structure. See https://issuetracker.google.com/issues/193896397 (which has links to older versions of the samples on 4.2) and this related issue: https://github.com/android/performance-samples/issues/88

Closing as we don't have plans to change this, but I'll keep responding if there are more questions.
